export default {
    SET_LOCALE: 'SET_LOCALE',
    SET_ANGULAR_OBJ: 'SET_ANGULAR_OBJ',
    TOGGLE_MENU_ITEM: 'TOGGLE_MENU_ITEM',
    UPDATE_SUBMENU_ITEMS: 'UPDATE_SUBMENU_ITEMS',
    ADD_TOP_LEVEL_LINK_FUNC: 'ADD_TOP_LEVEL_LINK_FUNC',
    LOG_METRIC: 'LOG_METRIC'
}
